Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
Internal Server Error: /auth/profil/admin3/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 79, in profilePage
    return render(request, 'log/profile-page.html', context)
  File "C:\python3.10\myenv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\python3.10\myenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\python3.10\myenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\python3.10\myenv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 116, in render
    url = self.url(context)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 113, in url
    return self.handle_simple(path)
  File "C:\python3.10\myenv\lib\site-packages\django\templatetags\static.py", line 129, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 203, in url
    return self._url(self.stored_name, name, force)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 182, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\staticfiles\storage.py", line 513, in stored_name
    raise ValueError(
ValueError: Missing staticfiles manifest entry for 'pics/favicon-alpha.png'
"GET /auth/profil/admin3/ HTTP/1.1" 500 1043
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /csapatunk/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /csapatunk/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /csapatunk/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /csapatunk/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /csapatunk/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /csapatunk/ HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
Internal Server Error: /auth/upload-article/
Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: loginsystem_articleuser.indeximg

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\python3.10\myenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\python3.10\myenv\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\python3.10\balzak\loginsystem\views.py", line 117, in uploadArticle
    instance.save()
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\python3.10\myenv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\python3.10\myenv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\python3.10\myenv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: loginsystem_articleuser.indeximg
"POST /auth/upload-article/ HTTP/1.1" 500 157833
